# Generated by Django 5.0.3 on 2024-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_friend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
