# Generated by Django 5.0.3 on 2024-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0002_friendship_is_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
