# Generated by Django 5.0.3 on 2024-04-02 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_cover_picture_and_more'),
        ('friendship_app', '0003_friendship_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
        ),
    ]
