# Generated by Django 5.0.3 on 2024-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0005_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
