# Generated by Django 4.2.7 on 2024-04-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0007_alter_room_user1_alter_room_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
