# Generated by Django 4.2.7 on 2024-04-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_time_alter_message_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
