# Generated by Django 5.0.3 on 2024-04-02 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_expiration_time', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.CharField(default='', max_length=100)),
                ('is_varified', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_bio', models.TextField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer_Not_Say', 'Prefer Not Say')], max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('account_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_picture', models.ImageField(default='global/images/avatar/image.jpeg', upload_to='profile_pictures/')),
                ('cover_picture', models.ImageField(default='global/images/avatar/cover.jpeg', upload_to='cover_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
