# Generated by Django 5.0.3 on 2024-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='online_status',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=30, null=True),
        ),
    ]
